### ISSUE TITLE
AWS throttle errors stops the reading logic

### ISSUE THREAD

**Issue by costimuraru** [davidmoten/rxjava2-aws#1]
Given the following code:

```java
Sqs.queueName("my-queue")
    // specify factory for Amazon SQS Client
   .sqsFactory(sqs)
   // log polls
   .logger(System.out::println)
   // get messages as observable
   .messages()
   // process the message
   .doOnNext(m -> System.out.println(m.message()))
   // delete the message (if processing succeeded)
   .doOnNext(m -> m.deleteMessage())
   // log any errors
   .blockingFirst();
```

This fails when `sqs.receiveMessage()` [0] fails with an Amazon exception (eg. AWS throttle [1]).

We tried adding a `.retry()` statement in the code above, but it seems that the `sqs` object gets shutdown [2] and the subsequent reads fail.

Any idea how to fix this?

[0]
https://github.com/davidmoten/rxjava2-aws/blob/master/src/main/java/com/github/davidmoten/rx2/aws/Sqs.java#L283

[1]
```
com.amazonaws.services.sqs.model.AmazonSQSException: We encountered an internal error. Please try again. (Service: AmazonSQS; Status Code: 500; Error Code: InternalError; Request ID: 55dce81b-8c1a-5324-bd88-bc1008db4399)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1658)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1322)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2073)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2049)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1513)
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1486)
	at com.github.davidmoten.rx2.aws.Sqs$ContinuousLongPollingSyncOnSubscribe.accept(Sqs.java:282)
	at com.github.davidmoten.rx2.aws.Sqs$ContinuousLongPollingSyncOnSubscribe.accept(Sqs.java:243)
	at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:62)
	at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:53)
	at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:109)
	at io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.request(FlowableUsing.java:158)
	at io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.request(FlowableUsing.java:158)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onSubscribe(FlowableFlatMapMaybe.java:107)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.onSubscribe(FlowableUsing.java:99)
	at io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.onSubscribe(FlowableUsing.java:99)
	at io.reactivex.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:52)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.Flowable.subscribe(Flowable.java:14365)
	at io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:74)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.Flowable.subscribe(Flowable.java:14365)
	at io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:74)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual(FlowableFlatMapMaybe.java:54)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:36)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.Flowable.subscribe(Flowable.java:14365)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

[2] https://github.com/davidmoten/rxjava2-aws/blob/master/src/main/java/com/github/davidmoten/rx2/aws/Sqs.java#L178

**Comment by davidmoten** [comment]
The `sqsFactory` argument is a factory for this reason. I suspect you are returning the same object every time the `sqsFactory` is called.

**Comment by davidmoten** [comment]
hmm perhaps I'm not rebuilding sqs object, I'll look at your PR

**Comment by davidmoten** [comment]
The code looks fine to me. Can you check that your sqsFactory recreates the client every call?

```java

    static Flowable<SqsMessage> messages(Callable<AmazonSQS> sqsFactory, Optional<Callable<AmazonS3>> s3Factory,
            String queueName, Optional<String> bucketName, Optional<Flowable<Integer>> waitTimesSeconds, Consumer<? super String> logger) {
        return Flowable.using(sqsFactory,
                sqs -> createFlowableWithSqs(sqs, s3Factory, sqsFactory, queueName, bucketName, waitTimesSeconds, logger),
                sqs -> sqs.shutdown());
    }
```

**Comment by davidmoten** [comment]
to be explicit, here's an example of how I use it:

```java
.sqsFactory(() -> (AmazonSQSClient) AmazonSQSClientBuilder //
                        .standard() //
                        .withRegion(Regions.AP_SOUTHEAST_2) //
                        .build())
```

**Comment by costimuraru** [comment]
Thanks, @davidmoten, for correcting. I actually coded that from Sublime, and it wasn't even compiling: `sqsFactory(sqs("us-east-1"))` instead of `sqsFactory(() -> sqs("us-east-1"))`

`sqsFactory(() -> sqs("us-east-1"))`
and
`sqsFactory(() -> AmazonSQSClientBuilder.standard().withRegion(region).build())`
are equivalent, so both should work.

Gave it a try and it behaves ok now. 

Btw, great job on the library - we are using it here https://github.com/adobe/shredder
